files:
  include: 'assets/stylesheets/**/*.scss'
rules:
  # Extends
  extends-before-declarations: 2
  placeholder-in-extend: 0

  # Style Guide
  brace-style: 2
  empty-args: 2
  indentation: 2
  leading-zero: 2
  mixin-name-format: 2
  nesting-depth: 0
  property-sort-order: 0
  pseudo-element: 2
  quotes: 2

  # Mixins
  mixins-before-declarations: 0

  # Disallows
  no-color-literals: 0
  no-duplicate-properties: 2
  no-important: 0
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 0
  no-vendor-prefixes: 0

  # Name Formats
  function-name-format: 2

  # Nesting
  force-attribute-nesting: 2
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Line Spacing
  empty-line-between-blocks: 2
  one-declaration-per-line: 2
  single-line-per-selector: 2

  # Inner Spacing
  space-after-comma: 2
  space-around-operator: 2
  space-before-brace: 2
