files:
  include:
    - 'assets/stylesheets/**/*.scss'
    - 'demo/tatami/src/client/css/**/*.scss'
rules:
  # Extends
  extends-before-declarations: 1
  placeholder-in-extend: 0

  # Style Guide
  brace-style: 1
  empty-args: 1
  indentation: 1
  leading-zero: 1
  mixin-name-format: 1
  nesting-depth: 0
  property-sort-order: 0
  pseudo-element: 1
  quotes: 1

  # Mixins
  mixins-before-declarations: 0

  # Disallows
  no-color-literals: 0
  no-color-keywords: 1
  no-duplicate-properties: 1
  no-important: 0
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-qualifying-elements: 0
  no-vendor-prefixes: 0

  # Name Formats
  function-name-format: 1

  # Nesting
  force-attribute-nesting: 1
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Line Spacing
  empty-line-between-blocks: 1
  one-declaration-per-line: 1
  single-line-per-selector: 1

  # Inner Spacing
  space-after-colon: 1
  space-after-comma: 1
  space-around-operator: 1
  space-before-brace: 1
